apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage.rpcSecretName" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
type: Opaque
stringData:
  rpcSecret: {{ include "garage.rpcSecret" . | quote }}
  adminToken: {{ include "garage.adminToken" . | quote }}
