{{- $accessKeyId := include "garage.upload.accessKeyId" . -}}
{{- $secretAccessKey := include "garage.upload.secretAccessKey" . -}}
{{- $endpoint := include "garage.s3Endpoint" . -}}
{{- $region := .Values.garage.s3.region -}}
{{- $bucket := .Values.upload.bucket -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage.uploadSecretName" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
  annotations:
    garage.deuxfleurs.fr/bucket: {{ $bucket | quote }}
    garage.deuxfleurs.fr/endpoint: {{ $endpoint | quote }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ $accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $secretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ $region | quote }}
  AWS_ENDPOINT_URL: {{ $endpoint | quote }}
  S3_BUCKET: {{ $bucket | quote }}
  S3_ENDPOINT: {{ $endpoint | quote }}
  S3_REGION: {{ $region | quote }}
  credentials: |
    [default]
    aws_access_key_id = {{ $accessKeyId }}
    aws_secret_access_key = {{ $secretAccessKey }}
    region = {{ $region }}
