apiVersion: v1
kind: Service
metadata:
  name: {{ include "garage.fullname" . }}-headless
  labels:
    {{- include "garage.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 3901
      targetPort: 3901
      protocol: TCP
      name: rpc
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}
